<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="servicemodel"
    nsURI="http://www.universaal.org/servicemodel" nsPrefix="servicemodel">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConsumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" upperBound="-1" eType="#//ServiceCall"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceBundle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceTypes" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceRealizations" upperBound="-1"
        eType="#//ServiceProvider" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceLevelRestrictions"
        upperBound="-1" eType="#//Restriction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceType" lowerBound="1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//InputValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//ServiceRequest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//Effect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restriction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumers" upperBound="-1"
        eType="#//ServiceConsumer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EffectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EffectType">
    <eLiterals name="CHANGE"/>
    <eLiterals name="ADD" value="1"/>
    <eLiterals name="REMOVE" value="2"/>
  </eClassifiers>
</ecore:EPackage>
