//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 09:18:23 PM CEST 
//


package org.universAAL.ucc.database.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for collectionValues complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="collectionValues">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="values" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="string" type="{}stringValue"/>
 *                     &lt;element name="integer" type="{}integerValue"/>
 *                     &lt;element name="boolean" type="{}booleanValue"/>
 *                     &lt;element name="double" type="{}doubleValue"/>
 *                     &lt;element name="calendar" type="{}calendarValue"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="multiselection" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "collectionValues", propOrder = {
    "values",
    "description",
    "label",
    "multiselection",
    "required"
})
public class CollectionValues {

    protected CollectionValues.Values values;
    protected String description;
    protected String label;
    protected boolean multiselection;
    protected boolean required;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "value_type", required = true)
    protected String valueType;

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionValues.Values }
     *     
     */
    public CollectionValues.Values getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionValues.Values }
     *     
     */
    public void setValues(CollectionValues.Values value) {
        this.values = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the multiselection property.
     * 
     */
    public boolean isMultiselection() {
        return multiselection;
    }

    /**
     * Sets the value of the multiselection property.
     * 
     */
    public void setMultiselection(boolean value) {
        this.multiselection = value;
    }

    /**
     * Gets the value of the required property.
     * 
     */
    public boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     */
    public void setRequired(boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueType(String value) {
        this.valueType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="string" type="{}stringValue"/>
     *           &lt;element name="integer" type="{}integerValue"/>
     *           &lt;element name="boolean" type="{}booleanValue"/>
     *           &lt;element name="double" type="{}doubleValue"/>
     *           &lt;element name="calendar" type="{}calendarValue"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stringOrIntegerOrBoolean"
    })
    public static class Values {

        @XmlElements({
            @XmlElement(name = "string", type = StringValue.class),
            @XmlElement(name = "integer", type = IntegerValue.class),
            @XmlElement(name = "boolean", type = BooleanValue.class),
            @XmlElement(name = "double", type = DoubleValue.class),
            @XmlElement(name = "calendar", type = CalendarValue.class)
        })
        protected List<SimpleObject> stringOrIntegerOrBoolean;

        /**
         * Gets the value of the stringOrIntegerOrBoolean property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stringOrIntegerOrBoolean property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStringOrIntegerOrBoolean().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StringValue }
         * {@link IntegerValue }
         * {@link BooleanValue }
         * {@link DoubleValue }
         * {@link CalendarValue }
         * 
         * 
         */
        public List<SimpleObject> getStringOrIntegerOrBoolean() {
            if (stringOrIntegerOrBoolean == null) {
                stringOrIntegerOrBoolean = new ArrayList<SimpleObject>();
            }
            return this.stringOrIntegerOrBoolean;
        }

    }

}
