//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 09:18:23 PM CEST 
//


package org.universAAL.ucc.database.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.universAAL.ucc.database.model.jaxb2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Profiles_QNAME = new QName("", "profiles");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.universAAL.ucc.database.model.jaxb2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Subprofile }
     * 
     */
    public Subprofile createSubprofile() {
        return new Subprofile();
    }

    /**
     * Create an instance of {@link CollectionValues }
     * 
     */
    public CollectionValues createCollectionValues() {
        return new CollectionValues();
    }

    /**
     * Create an instance of {@link OntologyInstance }
     * 
     */
    public OntologyInstance createOntologyInstance() {
        return new OntologyInstance();
    }

    /**
     * Create an instance of {@link EnumObject }
     * 
     */
    public EnumObject createEnumObject() {
        return new EnumObject();
    }

    /**
     * Create an instance of {@link Profiles }
     * 
     */
    public Profiles createProfiles() {
        return new Profiles();
    }

    /**
     * Create an instance of {@link CalendarValue }
     * 
     */
    public CalendarValue createCalendarValue() {
        return new CalendarValue();
    }

    /**
     * Create an instance of {@link SimpleObject }
     * 
     */
    public SimpleObject createSimpleObject() {
        return new SimpleObject();
    }

    /**
     * Create an instance of {@link IntegerValue }
     * 
     */
    public IntegerValue createIntegerValue() {
        return new IntegerValue();
    }

    /**
     * Create an instance of {@link StringValue }
     * 
     */
    public StringValue createStringValue() {
        return new StringValue();
    }

    /**
     * Create an instance of {@link DoubleValue }
     * 
     */
    public DoubleValue createDoubleValue() {
        return new DoubleValue();
    }

    /**
     * Create an instance of {@link BooleanValue }
     * 
     */
    public BooleanValue createBooleanValue() {
        return new BooleanValue();
    }

    /**
     * Create an instance of {@link Subprofile.Collections }
     * 
     */
    public Subprofile.Collections createSubprofileCollections() {
        return new Subprofile.Collections();
    }

    /**
     * Create an instance of {@link Subprofile.EnumObjects }
     * 
     */
    public Subprofile.EnumObjects createSubprofileEnumObjects() {
        return new Subprofile.EnumObjects();
    }

    /**
     * Create an instance of {@link Subprofile.SimpleObjects }
     * 
     */
    public Subprofile.SimpleObjects createSubprofileSimpleObjects() {
        return new Subprofile.SimpleObjects();
    }

    /**
     * Create an instance of {@link CollectionValues.Values }
     * 
     */
    public CollectionValues.Values createCollectionValuesValues() {
        return new CollectionValues.Values();
    }

    /**
     * Create an instance of {@link OntologyInstance.Subprofiles }
     * 
     */
    public OntologyInstance.Subprofiles createOntologyInstanceSubprofiles() {
        return new OntologyInstance.Subprofiles();
    }

    /**
     * Create an instance of {@link EnumObject.Values }
     * 
     */
    public EnumObject.Values createEnumObjectValues() {
        return new EnumObject.Values();
    }

    /**
     * Create an instance of {@link Profiles.OntologyInstances }
     * 
     */
    public Profiles.OntologyInstances createProfilesOntologyInstances() {
        return new Profiles.OntologyInstances();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Profiles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "profiles")
    public JAXBElement<Profiles> createProfiles(Profiles value) {
        return new JAXBElement<Profiles>(_Profiles_QNAME, Profiles.class, null, value);
    }

}
