//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.17 at 09:18:23 PM CEST 
//


package org.universAAL.ucc.database.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subprofile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subprofile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="collections" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="collection" type="{}collectionValues" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="enumObjects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="enumObject" type="{}enumObject" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="simpleObjects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="string" type="{}stringValue"/>
 *                     &lt;element name="integer" type="{}integerValue"/>
 *                     &lt;element name="boolean" type="{}booleanValue"/>
 *                     &lt;element name="double" type="{}doubleValue"/>
 *                     &lt;element name="calendar" type="{}calendarValue"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subprofile", propOrder = {
    "collections",
    "enumObjects",
    "simpleObjects"
})
public class Subprofile {

    protected Subprofile.Collections collections;
    protected Subprofile.EnumObjects enumObjects;
    protected Subprofile.SimpleObjects simpleObjects;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the collections property.
     * 
     * @return
     *     possible object is
     *     {@link Subprofile.Collections }
     *     
     */
    public Subprofile.Collections getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subprofile.Collections }
     *     
     */
    public void setCollections(Subprofile.Collections value) {
        this.collections = value;
    }

    /**
     * Gets the value of the enumObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Subprofile.EnumObjects }
     *     
     */
    public Subprofile.EnumObjects getEnumObjects() {
        return enumObjects;
    }

    /**
     * Sets the value of the enumObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subprofile.EnumObjects }
     *     
     */
    public void setEnumObjects(Subprofile.EnumObjects value) {
        this.enumObjects = value;
    }

    /**
     * Gets the value of the simpleObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Subprofile.SimpleObjects }
     *     
     */
    public Subprofile.SimpleObjects getSimpleObjects() {
        return simpleObjects;
    }

    /**
     * Sets the value of the simpleObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subprofile.SimpleObjects }
     *     
     */
    public void setSimpleObjects(Subprofile.SimpleObjects value) {
        this.simpleObjects = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="collection" type="{}collectionValues" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "collection"
    })
    public static class Collections {

        protected List<CollectionValues> collection;

        /**
         * Gets the value of the collection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the collection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCollection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CollectionValues }
         * 
         * 
         */
        public List<CollectionValues> getCollection() {
            if (collection == null) {
                collection = new ArrayList<CollectionValues>();
            }
            return this.collection;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="enumObject" type="{}enumObject" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enumObject"
    })
    public static class EnumObjects {

        protected List<EnumObject> enumObject;

        /**
         * Gets the value of the enumObject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the enumObject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEnumObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EnumObject }
         * 
         * 
         */
        public List<EnumObject> getEnumObject() {
            if (enumObject == null) {
                enumObject = new ArrayList<EnumObject>();
            }
            return this.enumObject;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="string" type="{}stringValue"/>
     *           &lt;element name="integer" type="{}integerValue"/>
     *           &lt;element name="boolean" type="{}booleanValue"/>
     *           &lt;element name="double" type="{}doubleValue"/>
     *           &lt;element name="calendar" type="{}calendarValue"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stringOrIntegerOrBoolean"
    })
    public static class SimpleObjects {

        @XmlElements({
            @XmlElement(name = "string", type = StringValue.class),
            @XmlElement(name = "integer", type = IntegerValue.class),
            @XmlElement(name = "boolean", type = BooleanValue.class),
            @XmlElement(name = "double", type = DoubleValue.class),
            @XmlElement(name = "calendar", type = CalendarValue.class)
        })
        protected List<SimpleObject> stringOrIntegerOrBoolean;

        /**
         * Gets the value of the stringOrIntegerOrBoolean property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stringOrIntegerOrBoolean property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStringOrIntegerOrBoolean().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StringValue }
         * {@link IntegerValue }
         * {@link BooleanValue }
         * {@link DoubleValue }
         * {@link CalendarValue }
         * 
         * 
         */
        public List<SimpleObject> getStringOrIntegerOrBoolean() {
            if (stringOrIntegerOrBoolean == null) {
                stringOrIntegerOrBoolean = new ArrayList<SimpleObject>();
            }
            return this.stringOrIntegerOrBoolean;
        }

    }

}
