
package org.universAAL.ucc.ustore.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OnlineStoreManager", targetNamespace = "http://tools.ustore.commerce.universaal.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnlineStoreManager {


    /**
     * 
     * @param port
     * @param userName
     * @param password
     * @param ipAddress
     * @return
     *     returns java.lang.String
     * @throws UAALException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerDeployManager", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.RegisterDeployManager")
    @ResponseWrapper(localName = "registerDeployManagerResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.RegisterDeployManagerResponse")
    public String registerDeployManager(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "ipAddress", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "port", targetNamespace = "")
        String port)
        throws UAALException_Exception
    ;

    /**
     * 
     * @param sessionKey
     * @return
     *     returns java.lang.String
     * @throws UAALException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserProfile", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.GetUserProfile")
    @ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.GetUserProfileResponse")
    public String getUserProfile(
        @WebParam(name = "sessionKey", targetNamespace = "")
        String sessionKey)
        throws UAALException_Exception
    ;

    /**
     * 
     * @param isFitToUser
     * @param sessionKey
     * @return
     *     returns java.lang.String
     * @throws UAALException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFreeAALServices", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.GetFreeAALServices")
    @ResponseWrapper(localName = "getFreeAALServicesResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.GetFreeAALServicesResponse")
    public String getFreeAALServices(
        @WebParam(name = "sessionKey", targetNamespace = "")
        String sessionKey,
        @WebParam(name = "isFitToUser", targetNamespace = "")
        boolean isFitToUser)
        throws UAALException_Exception
    ;

    /**
     * 
     * @param serviceId
     * @param sessionKey
     * @return
     *     returns java.lang.String
     * @throws UAALException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "purchaseFreeAALService", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.PurchaseFreeAALService")
    @ResponseWrapper(localName = "purchaseFreeAALServiceResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.PurchaseFreeAALServiceResponse")
    public String purchaseFreeAALService(
        @WebParam(name = "sessionKey", targetNamespace = "")
        String sessionKey,
        @WebParam(name = "serviceId", targetNamespace = "")
        String serviceId)
        throws UAALException_Exception
    ;

    /**
     * 
     * @param sessionKey
     * @return
     *     returns java.lang.String
     * @throws UAALException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPurchasedAALServices", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.GetPurchasedAALServices")
    @ResponseWrapper(localName = "getPurchasedAALServicesResponse", targetNamespace = "http://tools.ustore.commerce.universaal.org/", className = "org.universAAL.ucc.ustore.ws.GetPurchasedAALServicesResponse")
    public String getPurchasedAALServices(
        @WebParam(name = "sessionKey", targetNamespace = "")
        String sessionKey)
        throws UAALException_Exception
    ;

}
