
package org.universAAL.ucc.ustore.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "uAALException", targetNamespace = "http://tools.ustore.commerce.universaal.org/")
public class UAALException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UAALException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UAALException_Exception(String message, UAALException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UAALException_Exception(String message, UAALException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.universAAL.ucc.ustore.ws.UAALException
     */
    public UAALException getFaultInfo() {
        return faultInfo;
    }

}
