package org.universaal.tools.owl2javatransformation.model;

/**
 * this class contains the internal representation of a property.
 * It is used in representations of the ontology 
 * generated by the OntologyModel. 
 * Objects of this class are immutable.
 * @author wolf
 *
 */
public final class OntologyProperty extends OntologyEntity {
	
	private final String domain;
	private final String range;
	private final boolean isDataTypeProp;
	

	public OntologyProperty(String simpleName, String uri, String comment, 
			String domain, String range, boolean isDataTypeProp) {
		super(simpleName, uri, comment);
		this.domain = domain;
		this.range = range;
		this.isDataTypeProp = isDataTypeProp;
	}


	public String getDomain() {
		return domain;
	}


	public String getRange() {
		return range;
	}
	
	public boolean isDataTypeProp() {
		return isDataTypeProp;
	}
	
	
	
	
}
